# Generated by Django 5.1.5 on 2026-01-23 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_cart_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('card', 'Card (Mock)'), ('bkash', 'bKash (Mock)')], default='cod', max_length=20),
        ),
    ]
